# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - react-docker-compose

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://noderegistry1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bd1ed52e0845459f90e141059ce1d91c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71b442602f7543bc8e7ed18206034056 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: noderegistry1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd1ed52e0845459f90e141059ce1d91c }}/react-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'react-docker-compose'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7014a5eb9e0e4324b31c8abe0748e88e }}
        images: 'noderegistry1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd1ed52e0845459f90e141059ce1d91c }}/react-docker:${{ github.sha }}'